version: 2
updates:
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
  ignore:
  - dependency-name: anyhow
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: clap
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: semver
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: '*'
    update-types:
    - version-update:semver-patch
